### ISSUE TITLE
PGB mailing list is not set up

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-admin#12]
> <oslc-op-pgb@lists.oasis-open.org>: permission denied. Command output: Sorry,
    no mailbox here by that name. (#5.1.1) ERROR: postqmail-local Error #77

**Comment by berezovskyi** [comment]
@chet-ensign

**Comment by chet-ensign** [comment]
Just reporting in. Scott is getting this set up but having some complications with account set up with the service provider groups.io. I'll follow up with him today on progress.

**Comment by OASIS-OP-Admin** [comment]
The PGB mailing list is set up in groups.io. See https://lists.oasis-open-projects.org/g/oslc-op-pgb. 

The email address is oslc-op-pgb@lists.oasis-open-projects.org

List is set up so that:
- archives are publicly visible
- members require approval by moderators before joining
- subscriptions require approval of the moderators (the PGB members) 
- subscribers can post to the email list. non-subscribers can post but their messages will be moderated 
- moderators can edit the calendar; subscribers can view 
- moderators can open polls; subscribers can view/vote 

Once you all have tried it out and are comfortable with it, we can close this issue.

**Comment by berezovskyi** [comment]
Thanks a lot!
